name: Liquibase_Docker_GitHub-Hosted

on: [push]

# on:
#  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    environment: gcloud-dev0-temporal0-postgres
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'masterfile.xml'
          Username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          url: ${{ secrets.URL }}

