on: [push]

jobs:
  job_id:
    runs-on: ubuntu-latest
    environment: gcloud-dev0-temporal0-postgres
    name: Connect to gcloud VM Cluster using Service Account
    steps:
    - uses: 'actions/checkout@v2'
    - id: 'Liquibase Update Action'
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'masterfile.xml'
          Username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          url: ${{ secrets.URL }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: 'uc1-dev0'
        location: 'us-central1'

