on: [push]

jobs:
  job_id:
    runs-on: ubuntu-latest
    environment: gcloud-dev0-temporal0-postgres
    name: Connect to gcloud VM Cluster using Service Account
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0'
      with:
        cluster_name: 'uc1-dev0'
        location: 'us-central1'

    # The KUBECONFIG create pod by kubectl.
    - id: 'get-pods'
      #run: 'kubectl get pods;kubectl get nodes;'
      run: 'kubectl run ubuntu-liquibase-psql --image=ubuntu -- bash;sudo apt-get install postgresql-12;kubectl exec ubuntu-liquibase-psql -- /bin/bash;'

    - name: 'Liquibase Update Action'
      uses: 'liquibase/liquibase-github-action@v2'
      with:
        operation: 'update'
        classpath: 'example/changelogs'
        changeLogFile: 'masterfile.xml'
        Username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        url: ${{ secrets.CONN_URL }}
